name: Listen for triggers from participants to run an evaluation of their controller program

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"
