# run the evaluation of a robot controller and store the result in the competitors.txt file

name: Run Evaluation

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump event payload
        run: |
          jq '.organization.login' "$GITHUB_EVENT_PATH"
          jq '.sender.login' "$GITHUB_EVENT_PATH"
          #jq '.' "$GITHUB_EVENT_PATH"
          #jq '.repository.full_name' "$GITHUB_EVENT_PATH"
          #jq '.repository.private' "$GITHUB_EVENT_PATH"
          #'echo "field: ${{ github.event.client_payload.foo }}"'
          echo "client_payload: ${{ toJson(github.event.client_payload) }}"
