# run the evaluation of a robot controller and store the result in the competitors.txt file

name: Run Evaluation

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  evaluation:
    name: Evaluation Requested by a Participant
    runs-on: ubuntu-20.04
    steps:
      - name: Dump event payload
        run: |
          jq '.organization.login' "$GITHUB_EVENT_PATH"
          jq '.sender.login' "$GITHUB_EVENT_PATH"
          echo ${{ github.event.client_payload.repository }}
          echo ${{ github.event.sender.login }}
          echo ${{ github.event.organization.login }}
